import { NodeTypes } from '@xyflow/react'

// Import all node components
import { 
  StartEventNode, 
  EndEventNode, 
  TaskNode, 
  GatewayNode, 
  ProcessNode,
  IntermediateEventNode,
  TimerEventNode,
  MessageEventNode,
  ErrorEventNode,
  UserTaskNode,
  ServiceTaskNode,
  SignalEventNode,
  CancelEventNode,
  EscalationEventNode,
  NotificationEventNode,
  ManualTaskNode,
  ScriptTaskNode,
  SendTaskNode,
  ReceiveTaskNode,
  BusinessTaskNode,
  ProcessTaskNode,
  LoopTaskNode,
  ExclusiveGatewayNode,
  ParallelGatewayNode,
  EventBasedGatewayNode,
  InclusiveGatewayNode,
  ComplexGatewayNode,
  LoopProcessNode,
  MultiInstanceProcessNode,
  TransactionProcessNode,
  AdHocProcessNode,
  StorageNode,
  ServerNode,
  CloudStorageNode,
  ArchiveNode,
  FileSystemNode,
  DataStoreNode,
  DataObjectNode,
  WebServiceNode,
  RestApiNode,
  SoapApiNode,
  WebSocketNode,
  IntegrationNode,
  WebhookNode,
  UploadNode,
  DownloadNode,
  MessageNode,
  ChatNode,
  EmailNode,
  PhoneCallNode,
  VideoCallNode,
  VoiceMessageNode,
  NotificationNode,
  AnnouncementNode,
  SecureTaskNode,
  UnlockNode,
  AuthorizationNode,
  AuthenticationNode,
  VerifyUserNode,
  BlockUserNode,
  ShoppingCartNode,
  PaymentNode,
  TransactionNode,
  RevenueNode,
  AnalyticsNode,
  ReportNode,
  GoalNode,
  AchievementNode,
  ProductNode,
  DeliveryNode,
  DocumentNode,
  CreateFileNode,
  DeleteFileNode,
  VerifyFileNode,
  CopyNode,
  ClipboardNode,
  BookmarkNode,
  DesktopViewNode,
  MobileViewNode,
  LayoutNode,
  TextInputNode,
  DisplayNode,
  HideNode,
  ImageNode,
  CameraNode,
  LocationNode,
  MapNode,
  NavigationNode,
  DirectionNode,
  CheckpointNode,
  AddNode,
  SubtractNode,
  MultiplyNode,
  CalculateNode,
  PercentageNode,
  SearchNode,
  FilterNode,
  DeleteNode,
  EditNode,
  RefreshNode,
  SuccessNode,
  ErrorNode,
  InfoNode,
  WarningNode,
  CompleteNode,
  FailedNode,
  ProcessingNode,
  PendingNode,
} from './nodes'

import {
  DatabaseNode,
  ApiCallNode,
  ConditionalNode,
} from './nodes/CustomNodes'

import { GroupNode } from './nodes/GroupNode'

/**
 * Node types registry for ReactFlow
 */
export const nodeTypes: NodeTypes = {
  // Core BPMN nodes
  startEvent: StartEventNode,
  endEvent: EndEventNode,
  task: TaskNode,
  gateway: GatewayNode,
  process: ProcessNode,
  
  // Event nodes
  intermediateEvent: IntermediateEventNode,
  timerEvent: TimerEventNode,
  messageEvent: MessageEventNode,
  errorEvent: ErrorEventNode,
  signalEvent: SignalEventNode,
  cancelEvent: CancelEventNode,
  escalationEvent: EscalationEventNode,
  notificationEvent: NotificationEventNode,
  
  // Task nodes
  userTask: UserTaskNode,
  serviceTask: ServiceTaskNode,
  manualTask: ManualTaskNode,
  scriptTask: ScriptTaskNode,
  sendTask: SendTaskNode,
  receiveTask: ReceiveTaskNode,
  businessTask: BusinessTaskNode,
  processTask: ProcessTaskNode,
  loopTask: LoopTaskNode,
  
  // Gateway nodes
  exclusiveGateway: ExclusiveGatewayNode,
  parallelGateway: ParallelGatewayNode,
  eventBasedGateway: EventBasedGatewayNode,
  inclusiveGateway: InclusiveGatewayNode,
  complexGateway: ComplexGatewayNode,
  
  // Process nodes
  loopProcess: LoopProcessNode,
  multiInstanceProcess: MultiInstanceProcessNode,
  transactionProcess: TransactionProcessNode,
  adHocProcess: AdHocProcessNode,
  
  // Data & Storage nodes
  database: DatabaseNode,
  storage: StorageNode,
  server: ServerNode,
  cloudStorage: CloudStorageNode,
  archive: ArchiveNode,
  fileSystem: FileSystemNode,
  dataStore: DataStoreNode,
  dataObject: DataObjectNode,
  
  // Integration nodes
  apiCall: ApiCallNode,
  webService: WebServiceNode,
  restApi: RestApiNode,
  soapApi: SoapApiNode,
  webSocket: WebSocketNode,
  integration: IntegrationNode,
  webhook: WebhookNode,
  upload: UploadNode,
  download: DownloadNode,
  
  // Communication nodes
  message: MessageNode,
  chat: ChatNode,
  email: EmailNode,
  phoneCall: PhoneCallNode,
  videoCall: VideoCallNode,
  voiceMessage: VoiceMessageNode,
  notification: NotificationNode,
  announcement: AnnouncementNode,
  
  // Security nodes
  secureTask: SecureTaskNode,
  unlock: UnlockNode,
  authorization: AuthorizationNode,
  authentication: AuthenticationNode,
  verifyUser: VerifyUserNode,
  blockUser: BlockUserNode,
  
  // Business nodes
  shoppingCart: ShoppingCartNode,
  payment: PaymentNode,
  transaction: TransactionNode,
  revenue: RevenueNode,
  analytics: AnalyticsNode,
  report: ReportNode,
  goal: GoalNode,
  achievement: AchievementNode,
  product: ProductNode,
  delivery: DeliveryNode,
  
  // Document nodes
  document: DocumentNode,
  createFile: CreateFileNode,
  deleteFile: DeleteFileNode,
  verifyFile: VerifyFileNode,
  copy: CopyNode,
  clipboard: ClipboardNode,
  bookmark: BookmarkNode,
  
  // UI nodes
  desktopView: DesktopViewNode,
  mobileView: MobileViewNode,
  layout: LayoutNode,
  textInput: TextInputNode,
  display: DisplayNode,
  hide: HideNode,
  image: ImageNode,
  camera: CameraNode,
  
  // Location nodes
  location: LocationNode,
  map: MapNode,
  navigation: NavigationNode,
  direction: DirectionNode,
  checkpoint: CheckpointNode,
  
  // Operation nodes
  add: AddNode,
  subtract: SubtractNode,
  multiply: MultiplyNode,
  calculate: CalculateNode,
  percentage: PercentageNode,
  search: SearchNode,
  filter: FilterNode,
  delete: DeleteNode,
  edit: EditNode,
  refresh: RefreshNode,
  
  // Status nodes
  success: SuccessNode,
  error: ErrorNode,
  info: InfoNode,
  warning: WarningNode,
  complete: CompleteNode,
  failed: FailedNode,
  processing: ProcessingNode,
  pending: PendingNode,
  
  // Custom nodes
  conditional: ConditionalNode,
  
  // Container/Group node
  group: GroupNode,
}
