import { IsString, IsNotEmpty, IsArray, ValidateNested, IsOptional, IsNumber, IsBoolean, IsEnum } from 'class-validator';
import { Type } from 'class-transformer';
import {  HandlePosition, PathType } from '@prisma/client';

/**
 * Flow action types for tracking changes
 */
export enum FlowAction {
  ADD = 'ADD',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
}

/**
 * DTO for node styling
 */
export class NodeStyleDto {
  @IsOptional()
  @IsString()
  backgroundColor?: string;

  @IsOptional()
  @IsString()
  borderColor?: string;

  @IsOptional()
  borderWidth?: number | string;

  @IsOptional()
  borderRadius?: number | string;

  @IsOptional()
  @IsString()
  color?: string;

  @IsOptional()
  fontSize?: number | string;

  @IsOptional()
  @IsString()
  fontWeight?: string;

  @IsOptional()
  @IsString()
  textAlign?: string;

  @IsOptional()
  opacity?: number | string;
}

/**
 * DTO for saving a flow node
 */
export class SaveNodeDto {
  @IsOptional()
  @IsString()
  id?: string; // Optional - auto-generated by Prisma for new nodes (action=ADD)

  @IsOptional()
  @IsEnum(FlowAction)
  action?: FlowAction;

  @IsNotEmpty()
  type: string;

  @IsString()
  @IsNotEmpty()
  label: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsNumber()
  positionX: number;

  @IsNumber()
  positionY: number;

  @IsOptional()
  @IsNumber()
  width?: number;

  @IsOptional()
  @IsNumber()
  height?: number;

  @IsOptional()
  @IsNumber()
  zIndex?: number;

  @IsOptional()
  @IsString()
  parentNodeId?: string;

  @IsOptional()
  @IsString()
  groupId?: string;

  @IsOptional()
  @IsEnum(HandlePosition)
  sourcePosition?: HandlePosition;

  @IsOptional()
  @IsEnum(HandlePosition)
  targetPosition?: HandlePosition;

  @IsOptional()
  @IsBoolean()
  isConnectable?: boolean;

  @IsOptional()
  @IsBoolean()
  isDraggable?: boolean;

  @IsOptional()
  @IsBoolean()
  isSelectable?: boolean;

  @IsOptional()
  @ValidateNested()
  @Type(() => NodeStyleDto)
  style?: NodeStyleDto;

  @IsOptional()
  data?: any; // Additional custom data
}

/**
 * DTO for edge styling
 */
export class EdgeStyleDto {
  @IsOptional()
  @IsString()
  strokeColor?: string;

  @IsOptional()
  strokeWidth?: number | string;

  @IsOptional()
  @IsString()
  strokeDasharray?: string;
}

/**
 * DTO for saving a flow edge
 */
export class SaveEdgeDto {
  @IsOptional()
  @IsString()
  id?: string; // Optional - auto-generated by Prisma for new edges (action=ADD)

  @IsOptional()
  @IsEnum(FlowAction)
  action?: FlowAction;

  @IsString()
  @IsNotEmpty()
  source: string; // Node ID

  @IsString()
  @IsNotEmpty()
  target: string; // Node ID

  @IsOptional()
  type?: string;

  @IsOptional()
  @IsString()
  label?: string;

  @IsOptional()
  @IsBoolean()
  animated?: boolean;

  @IsOptional()
  @IsEnum(PathType)
  pathType?: PathType;

  @IsOptional()
  @IsString()
  sourceHandle?: string;

  @IsOptional()
  @IsString()
  targetHandle?: string;

  @IsOptional()
  @ValidateNested()
  @Type(() => EdgeStyleDto)
  style?: EdgeStyleDto;

  @IsOptional()
  data?: any; // Additional custom data
}

/**
 * DTO for saving complete flow diagram
 */
export class SaveFlowDto {
  @IsString()
  @IsNotEmpty()
  processId: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SaveNodeDto)
  nodes: SaveNodeDto[];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SaveEdgeDto)
  edges: SaveEdgeDto[];

  @IsOptional()
  @IsString()
  changesLog?: string; // Description of changes made
}

/**
 * DTO for updating flow layout settings
 */
export class UpdateFlowLayoutDto {
  @IsOptional()
  @IsNumber()
  zoom?: number;

  @IsOptional()
  @IsNumber()
  viewportX?: number;

  @IsOptional()
  @IsNumber()
  viewportY?: number;

  @IsOptional()
  snapToGrid?: boolean;

  @IsOptional()
  @IsNumber()
  gridSize?: number;
}
